export const typeIcons = {
  bug: "/img/icons/bug.svg",
  dark: "/img/icons/dark.svg",
  dragon: "/img/icons/dragon.svg",
  electric: "/img/icons/electric.svg",
  fairy: "/img/icons/fairy.svg",
  fighting: "/img/icons/fighting.svg",
  fire: "/img/icons/fire.svg",
  flying: "/img/icons/flying.svg",
  ghost: "/img/icons/ghost.svg",
  grass: "/img/icons/grass.svg",
  ground: "/img/icons/ground.svg",
  ice: "/img/icons/ice.svg",
  normal: "/img/icons/normal.svg",
  poison: "/img/icons/poison.svg",
  psychic: "/img/icons/psychic.svg",
  rock: "/img/icons/rock.svg",
  steel: "/img/icons/steel.svg",
  water: "/img/icons/water.svg",
};
