export const typeIcons = {
  bug: "/img/icons/bug.svg",
  dark: "/img/icons/dark.svg",
  dragon: "/img/icons/dragon.svg",
  electric: "/img/icons/electric.svg",
  fairy: "/img/icons/fairy.svg",
  fighting: "/img/icons/fighting.svg",
  fire: "/img/icons/fire.svg",
  flying: "/img/icons/flying.svg",
  ghost: "/img/icons/ghost.svg",
  grass: "/img/icons/grass.svg",
  ground: "/img/icons/ground.svg",
  ice: "/img/icons/ice.svg",
  normal: "/img/icons/normal.svg",
  poison: "/img/icons/poison.svg",
  psychic: "/img/icons/psychic.svg",
  rock: "/img/icons/rock.svg",
  steel: "/img/icons/steel.svg",
  water: "/img/icons/water.svg",
};

export const typeBackgroundClasses = {
  bug: "bg-bug",
  dark: "bg-dark",
  dragon: "bg-dragon",
  electric: "bg-electric",
  fairy: "bg-fairy",
  fighting: "bg-fighting",
  fire: "bg-fire",
  flying: "bg-flying",
  ghost: "bg-ghost",
  grass: "bg-grass",
  ground: "bg-ground",
  ice: "bg-ice",
  normal: "bg-normal",
  poison: "bg-poison",
  psychic: "bg-psychic",
  rock: "bg-rock",
  steel: "bg-steel",
  water: "bg-water",
};
